
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute("e39ae588-6791-42c1-a690-9f41e79e689f")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class HưngVũEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new HưngVũEntities object using the connection string found in the 'HưngVũEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=HưngVũEntities", "HưngVũEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new HưngVũEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "HưngVũEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new HưngVũEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "HưngVũEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagram)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagram)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagram)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property VhhKhoas() As ObjectSet(Of VhhKhoa)
        Get
            If (_VhhKhoas Is Nothing) Then
                _VhhKhoas = MyBase.CreateObjectSet(Of VhhKhoa)("VhhKhoas")
            End If
            Return _VhhKhoas
        End Get
    End Property

    Private _VhhKhoas As ObjectSet(Of VhhKhoa)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property VhhSinhViens() As ObjectSet(Of VhhSinhVien)
        Get
            If (_VhhSinhViens Is Nothing) Then
                _VhhSinhViens = MyBase.CreateObjectSet(Of VhhSinhVien)("VhhSinhViens")
            End If
            Return _VhhSinhViens
        End Get
    End Property

    Private _VhhSinhViens As ObjectSet(Of VhhSinhVien)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagram As sysdiagram)
        MyBase.AddObject("sysdiagrams", sysdiagram)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the VhhKhoas EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVhhKhoas(ByVal vhhKhoa As VhhKhoa)
        MyBase.AddObject("VhhKhoas", vhhKhoa)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the VhhSinhViens EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVhhSinhViens(ByVal vhhSinhVien As VhhSinhVien)
        MyBase.AddObject("VhhSinhViens", vhhSinhVien)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HưngVũModel", Name:="sysdiagram")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagram
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagram object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagram(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagram
        Dim sysdiagram as sysdiagram = New sysdiagram
        sysdiagram.name = name
        sysdiagram.principal_id = principal_id
        sysdiagram.diagram_id = diagram_id
        Return sysdiagram
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false, "name")
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value, "principal_id")
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value, "diagram_id")
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value, "version")
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true, "definition")
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HưngVũModel", Name:="VhhKhoa")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class VhhKhoa
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new VhhKhoa object.
    ''' </summary>
    ''' <param name="vhhMaKH">Initial value of the VhhMaKH property.</param>
    Public Shared Function CreateVhhKhoa(vhhMaKH As Global.System.String) As VhhKhoa
        Dim vhhKhoa as VhhKhoa = New VhhKhoa
        vhhKhoa.VhhMaKH = vhhMaKH
        Return vhhKhoa
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VhhMaKH() As Global.System.String
        Get
            Return _VhhMaKH
        End Get
        Set
            If (_VhhMaKH <> Value) Then
                OnVhhMaKHChanging(value)
                ReportPropertyChanging("VhhMaKH")
                _VhhMaKH = StructuralObject.SetValidValue(value, false, "VhhMaKH")
                ReportPropertyChanged("VhhMaKH")
                OnVhhMaKHChanged()
            End If
        End Set
    End Property

    Private _VhhMaKH As Global.System.String
    Private Partial Sub OnVhhMaKHChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhMaKHChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhTenKH() As Global.System.String
        Get
            Return _VhhTenKH
        End Get
        Set
            OnVhhTenKHChanging(value)
            ReportPropertyChanging("VhhTenKH")
            _VhhTenKH = StructuralObject.SetValidValue(value, true, "VhhTenKH")
            ReportPropertyChanged("VhhTenKH")
            OnVhhTenKHChanged()
        End Set
    End Property

    Private _VhhTenKH As Global.System.String
    Private Partial Sub OnVhhTenKHChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhTenKHChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhTrangThai() As Nullable(Of Global.System.Boolean)
        Get
            Return _VhhTrangThai
        End Get
        Set
            OnVhhTrangThaiChanging(value)
            ReportPropertyChanging("VhhTrangThai")
            _VhhTrangThai = StructuralObject.SetValidValue(value, "VhhTrangThai")
            ReportPropertyChanged("VhhTrangThai")
            OnVhhTrangThaiChanged()
        End Set
    End Property

    Private _VhhTrangThai As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnVhhTrangThaiChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnVhhTrangThaiChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="HưngVũModel", Name:="VhhSinhVien")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class VhhSinhVien
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new VhhSinhVien object.
    ''' </summary>
    ''' <param name="vhhMaSV">Initial value of the VhhMaSV property.</param>
    Public Shared Function CreateVhhSinhVien(vhhMaSV As Global.System.String) As VhhSinhVien
        Dim vhhSinhVien as VhhSinhVien = New VhhSinhVien
        vhhSinhVien.VhhMaSV = vhhMaSV
        Return vhhSinhVien
    End Function

    #End Region

    #Region "Simple Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property VhhMaSV() As Global.System.String
        Get
            Return _VhhMaSV
        End Get
        Set
            If (_VhhMaSV <> Value) Then
                OnVhhMaSVChanging(value)
                ReportPropertyChanging("VhhMaSV")
                _VhhMaSV = StructuralObject.SetValidValue(value, false, "VhhMaSV")
                ReportPropertyChanged("VhhMaSV")
                OnVhhMaSVChanged()
            End If
        End Set
    End Property

    Private _VhhMaSV As Global.System.String
    Private Partial Sub OnVhhMaSVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhMaSVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhHoSV() As Global.System.String
        Get
            Return _VhhHoSV
        End Get
        Set
            OnVhhHoSVChanging(value)
            ReportPropertyChanging("VhhHoSV")
            _VhhHoSV = StructuralObject.SetValidValue(value, true, "VhhHoSV")
            ReportPropertyChanged("VhhHoSV")
            OnVhhHoSVChanged()
        End Set
    End Property

    Private _VhhHoSV As Global.System.String
    Private Partial Sub OnVhhHoSVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhHoSVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhTenSV() As Global.System.String
        Get
            Return _VhhTenSV
        End Get
        Set
            OnVhhTenSVChanging(value)
            ReportPropertyChanging("VhhTenSV")
            _VhhTenSV = StructuralObject.SetValidValue(value, true, "VhhTenSV")
            ReportPropertyChanged("VhhTenSV")
            OnVhhTenSVChanged()
        End Set
    End Property

    Private _VhhTenSV As Global.System.String
    Private Partial Sub OnVhhTenSVChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhTenSVChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhNgaySinh() As Nullable(Of Global.System.DateTime)
        Get
            Return _VhhNgaySinh
        End Get
        Set
            OnVhhNgaySinhChanging(value)
            ReportPropertyChanging("VhhNgaySinh")
            _VhhNgaySinh = StructuralObject.SetValidValue(value, "VhhNgaySinh")
            ReportPropertyChanged("VhhNgaySinh")
            OnVhhNgaySinhChanged()
        End Set
    End Property

    Private _VhhNgaySinh As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnVhhNgaySinhChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnVhhNgaySinhChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhPhai() As Nullable(Of Global.System.Boolean)
        Get
            Return _VhhPhai
        End Get
        Set
            OnVhhPhaiChanging(value)
            ReportPropertyChanging("VhhPhai")
            _VhhPhai = StructuralObject.SetValidValue(value, "VhhPhai")
            ReportPropertyChanged("VhhPhai")
            OnVhhPhaiChanged()
        End Set
    End Property

    Private _VhhPhai As Nullable(Of Global.System.Boolean)
    Private Partial Sub OnVhhPhaiChanging(value As Nullable(Of Global.System.Boolean))
    End Sub

    Private Partial Sub OnVhhPhaiChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhPhone() As Global.System.String
        Get
            Return _VhhPhone
        End Get
        Set
            OnVhhPhoneChanging(value)
            ReportPropertyChanging("VhhPhone")
            _VhhPhone = StructuralObject.SetValidValue(value, true, "VhhPhone")
            ReportPropertyChanged("VhhPhone")
            OnVhhPhoneChanged()
        End Set
    End Property

    Private _VhhPhone As Global.System.String
    Private Partial Sub OnVhhPhoneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhPhoneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhEmail() As Global.System.String
        Get
            Return _VhhEmail
        End Get
        Set
            OnVhhEmailChanging(value)
            ReportPropertyChanging("VhhEmail")
            _VhhEmail = StructuralObject.SetValidValue(value, true, "VhhEmail")
            ReportPropertyChanged("VhhEmail")
            OnVhhEmailChanged()
        End Set
    End Property

    Private _VhhEmail As Global.System.String
    Private Partial Sub OnVhhEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhEmailChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property VhhMaKH() As Global.System.String
        Get
            Return _VhhMaKH
        End Get
        Set
            OnVhhMaKHChanging(value)
            ReportPropertyChanging("VhhMaKH")
            _VhhMaKH = StructuralObject.SetValidValue(value, true, "VhhMaKH")
            ReportPropertyChanged("VhhMaKH")
            OnVhhMaKHChanged()
        End Set
    End Property

    Private _VhhMaKH As Global.System.String
    Private Partial Sub OnVhhMaKHChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnVhhMaKHChanged()
    End Sub

    #End Region

End Class

#End Region

