'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VhhSinhVien
    Public Property VhhMaSV As String
    Public Property VhhHoSV As String
    Public Property VhhTenSV As String
    Public Property VhhNgaySinh As Nullable(Of Date)
    Public Property VhhPhai As Nullable(Of Boolean)
    Public Property VhhPhone As String
    Public Property VhhEmail As String
    Public Property VhhMaKH As String

End Class
